#!/usr/bin/env python3
"""
OWL File Comparison Tool
Compares two OWL ontologies and generates detailed difference reports.

Fixes vs original:
  - BUG FIX: oprops_f1 / dprops_f1 were always 0 due to wrong key name
    generated by elem_type.split('_')[0]  ('object', 'data' instead of
    'oprops', 'dprops').  Now uses an explicit mapping.
  - BUG FIX: restriction_axioms were counted but never included in
    overall_f1.  Now included.
  - NEW: Precision and Recall added to metrics dict and Excel summary.
  - NEW: "Mismatch Notes" Excel sheet with plain-English diagnosis of
    every discrepancy.
  - NEW: restriction_f1 added to metrics.
  - IMPROVED: Excel Summary sheet now shows Gold / Extracted / TP / FP /
    FN / Precision / Recall / F1 for every element type.
"""

import json
import csv
import sys
from pathlib import Path
from rdflib import Graph, RDF, RDFS, OWL, Namespace, URIRef
from collections import defaultdict

try:
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False


# ─── Helpers ─────────────────────────────────────────────────────────────────

def normalize_uri(uri):
    """Extract local name from URI for comparison."""
    uri_str = str(uri)
    if "#" in uri_str:
        return uri_str.split("#")[-1]
    elif "/" in uri_str:
        return uri_str.split("/")[-1]
    return uri_str


def _prf(correct: int, gold_count: int, ext_count: int) -> dict:
    """Return precision, recall, F1 given counts."""
    precision = correct / ext_count if ext_count > 0 else 1.0
    recall    = correct / gold_count if gold_count > 0 else 1.0
    f1 = (2 * precision * recall / (precision + recall)
          if (precision + recall) > 0 else 0.0)
    return {
        "precision": round(precision, 4),
        "recall":    round(recall,    4),
        "f1":        round(f1,        4),
    }


# ─── Ontology extraction ─────────────────────────────────────────────────────

def extract_ontology_elements(owl_file):
    """Extract classes, properties, restrictions from OWL file."""
    g = Graph()
    try:
        g.parse(owl_file, format='xml')
    except Exception as e:
        print(f"[!] Error parsing {owl_file}: {e}")
        return None

    elements = {
        "classes":           set(),
        "object_properties": set(),
        "data_properties":   set(),
        "restrictions":      [],
        "triplets":          [],
    }

    for cls  in g.subjects(RDF.type, OWL.Class):
        elements["classes"].add(normalize_uri(cls))
    for prop in g.subjects(RDF.type, OWL.ObjectProperty):
        elements["object_properties"].add(normalize_uri(prop))
    for prop in g.subjects(RDF.type, OWL.DatatypeProperty):
        elements["data_properties"].add(normalize_uri(prop))

    for restr in g.subjects(RDF.type, OWL.Restriction):
        restriction = {"type": "Restriction", "on_property": None,
                       "restriction_details": {}}
        for prop in g.objects(restr, OWL.onProperty):
            restriction["on_property"] = normalize_uri(prop)
        for v in g.objects(restr, OWL.someValuesFrom):
            restriction["restriction_details"]["someValuesFrom"] = normalize_uri(v)
        for v in g.objects(restr, OWL.allValuesFrom):
            restriction["restriction_details"]["allValuesFrom"] = normalize_uri(v)
        for v in g.objects(restr, OWL.minCardinality):
            restriction["restriction_details"]["minCardinality"] = str(v)
        for v in g.objects(restr, OWL.maxCardinality):
            restriction["restriction_details"]["maxCardinality"] = str(v)
        for v in g.objects(restr, OWL.cardinality):
            restriction["restriction_details"]["cardinality"] = str(v)
        if restriction["on_property"]:
            elements["restrictions"].append(restriction)

    for s, p, o in g.triples((None, None, None)):
        elements["triplets"].append({
            "subject":   normalize_uri(s),
            "predicate": normalize_uri(p),
            "object":    normalize_uri(o),
        })

    return elements


# ─── Restriction matching ─────────────────────────────────────────────────────

def _restr_key(r: dict) -> tuple:
    """Canonical key for a restriction."""
    prop = r.get("on_property", "")
    details = r.get("restriction_details", {})
    return (prop, tuple(sorted(details.items())))


def _match_restrictions(gold_list, ext_list):
    """Return (matched_gold, unmatched_gold, unmatched_ext)."""
    gold_keys = [_restr_key(r) for r in gold_list]
    ext_keys  = [_restr_key(r) for r in ext_list]
    matched_gold, unmatched_gold, unmatched_ext = [], [], []
    used = set()
    for i, gk in enumerate(gold_keys):
        found = False
        for j, ek in enumerate(ext_keys):
            if j not in used and gk == ek:
                matched_gold.append(gold_list[i])
                used.add(j)
                found = True
                break
        if not found:
            unmatched_gold.append(gold_list[i])
    for j, r in enumerate(ext_list):
        if j not in used:
            unmatched_ext.append(r)
    return matched_gold, unmatched_gold, unmatched_ext


# ─── Main comparison ──────────────────────────────────────────────────────────

def compare_ontologies(extracted_file, gold_file):
    """Compare two OWL ontologies; return structured comparison dict."""
    ext  = extract_ontology_elements(extracted_file)
    gold = extract_ontology_elements(gold_file)
    if not ext or not gold:
        return None

    comparison = {}

    # ── Classes / Object Properties / Data Properties ─────────────────────
    for key in ("classes", "object_properties", "data_properties"):
        g_set = gold[key]
        e_set = ext[key]
        comparison[key] = {
            "gold":      sorted(g_set),
            "extracted": sorted(e_set),
            "missing":   sorted(g_set - e_set),
            "extra":     sorted(e_set - g_set),
            "correct":   sorted(g_set & e_set),
        }

    # ── Restrictions ─────────────────────────────────────────────────────
    matched, missing_r, extra_r = _match_restrictions(
        gold["restrictions"], ext["restrictions"])
    comparison["restrictions"] = {
        "gold_count":         len(gold["restrictions"]),
        "extracted_count":    len(ext["restrictions"]),
        "correct_count":      len(matched),
        "missing_count":      len(missing_r),
        "extra_count":        len(extra_r),
        "gold_details":       gold["restrictions"],
        "extracted_details":  ext["restrictions"],
        "missing_details":    missing_r,
        "extra_details":      extra_r,
        "matched_details":    matched,
    }

    # ── Metrics (FIXED: explicit keys, includes restrictions) ─────────────
    # Key mapping: element key → metric prefix
    _key_map = {
        "classes":           "classes",
        "object_properties": "oprops",   # ← was broken (gave "object")
        "data_properties":   "dprops",   # ← was broken (gave "data")
    }
    metrics = {}
    for key, prefix in _key_map.items():
        g_n = len(comparison[key]["gold"])
        e_n = len(comparison[key]["extracted"])
        c_n = len(comparison[key]["correct"])
        prf = _prf(c_n, g_n, e_n)
        metrics[f"{prefix}_precision"] = prf["precision"]
        metrics[f"{prefix}_recall"]    = prf["recall"]
        metrics[f"{prefix}_f1"]        = prf["f1"]

    # Restriction F1 (NEW)
    r = comparison["restrictions"]
    r_prf = _prf(r["correct_count"], r["gold_count"], r["extracted_count"])
    metrics["restrictions_precision"] = r_prf["precision"]
    metrics["restrictions_recall"]    = r_prf["recall"]
    metrics["restrictions_f1"]        = r_prf["f1"]

    # Overall F1 — now includes restrictions  (FIXED: was missing restrictions)
    gold_total    = (len(gold["classes"]) + len(gold["object_properties"])
                     + len(gold["data_properties"]) + len(gold["restrictions"]))
    ext_total     = (len(ext["classes"]) + len(ext["object_properties"])
                     + len(ext["data_properties"]) + len(ext["restrictions"]))
    correct_total = (len(comparison["classes"]["correct"])
                     + len(comparison["object_properties"]["correct"])
                     + len(comparison["data_properties"]["correct"])
                     + r["correct_count"])
    o_prf = _prf(correct_total, gold_total, ext_total)
    metrics["overall_precision"] = o_prf["precision"]
    metrics["overall_recall"]    = o_prf["recall"]
    metrics["overall_f1"]        = o_prf["f1"]

    comparison["metrics"] = metrics

    # ── Mismatch Notes (NEW) ───────────────────────────────────────────────
    comparison["mismatch_notes"] = _build_mismatch_notes(comparison)

    return comparison


# ─── Mismatch notes ──────────────────────────────────────────────────────────

def _restr_human(r: dict) -> str:
    """Human-readable description of a restriction."""
    prop = r.get("on_property", "?")
    details = r.get("restriction_details", {})
    parts = []
    if "someValuesFrom" in details:
        parts.append(f"some {details['someValuesFrom']}")
    if "allValuesFrom" in details:
        parts.append(f"only {details['allValuesFrom']}")
    if "minCardinality" in details:
        parts.append(f"min cardinality {details['minCardinality']}")
    if "maxCardinality" in details:
        parts.append(f"max cardinality {details['maxCardinality']}")
    if "cardinality" in details:
        parts.append(f"exactly {details['cardinality']}")
    detail_str = ", ".join(parts) if parts else str(details)
    return f"subClassOf ({prop} {detail_str})"


def _build_mismatch_notes(comparison: dict) -> list:
    """
    Generate a list of plain-English mismatch notes.
    Each entry: {category, severity, element, note}
    """
    notes = []

    label_map = {
        "classes":           "Class",
        "object_properties": "Object Property",
        "data_properties":   "Data Property",
    }

    for key, label in label_map.items():
        for item in comparison[key]["missing"]:
            notes.append({
                "category": label,
                "severity": "FALSE NEGATIVE",
                "element":  item,
                "note": (f"'{item}' is in the gold standard but was NOT extracted. "
                         f"The extractor missed this {label.lower()}."),
            })
        for item in comparison[key]["extra"]:
            notes.append({
                "category": label,
                "severity": "FALSE POSITIVE",
                "element":  item,
                "note": (f"'{item}' was extracted but does NOT exist in the gold "
                         f"standard. This is a hallucinated {label.lower()}."),
            })

    # Restrictions
    for r in comparison["restrictions"]["missing_details"]:
        desc = _restr_human(r)
        notes.append({
            "category": "Restriction Axiom",
            "severity": "FALSE NEGATIVE",
            "element":  desc,
            "note": (f"Restriction axiom '{desc}' is defined in the gold OWL "
                     f"(via owl:Restriction / rdfs:subClassOf) but was NOT "
                     f"extracted. These axioms are typically invisible in "
                     f"standard OWL diagrams — this is a structural limitation "
                     f"of visual extraction."),
        })
    for r in comparison["restrictions"]["extra_details"]:
        desc = _restr_human(r)
        notes.append({
            "category": "Restriction Axiom",
            "severity": "FALSE POSITIVE",
            "element":  desc,
            "note": (f"Restriction axiom '{desc}' was extracted but does NOT "
                     f"exist in the gold standard. Check for misinterpreted "
                     f"diagram elements."),
        })

    if not notes:
        notes.append({
            "category": "—",
            "severity": "NONE",
            "element":  "—",
            "note": ("No mismatches found in classes, object properties, or data "
                     "properties. Restriction axioms may still differ — see "
                     "Restrictions sheet."),
        })

    return notes


# ─── Save results ─────────────────────────────────────────────────────────────

def save_results(comparison, output_dir):
    """Save comparison results to JSON, text, CSV and Excel."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # JSON
    json_file = output_path / "comparison_report.json"
    with open(json_file, 'w') as f:
        json.dump(comparison, f, indent=2)
    print(f"  JSON  : {json_file}")

    # Text report
    text_file = output_path / "comparison_report.txt"
    _save_text_report(comparison, text_file)
    print(f"  Text  : {text_file}")

    # CSV differences
    csv_file = output_path / "differences.csv"
    _save_csv(comparison, csv_file)
    print(f"  CSV   : {csv_file}")

    # Excel
    if HAS_OPENPYXL:
        excel_file = output_path / "comparison_report.xlsx"
        save_excel_report(comparison, excel_file)
        print(f"  Excel : {excel_file}")
    else:
        print("[!] openpyxl not installed — skipping Excel. Run: pip install openpyxl")


def _save_text_report(comparison, text_file):
    with open(text_file, 'w') as f:
        sep = "=" * 80
        thin = "-" * 80
        f.write(sep + "\nOWL ONTOLOGY COMPARISON REPORT\n" + sep + "\n\n")

        for key, label in [("classes", "CLASSES"),
                            ("object_properties", "OBJECT PROPERTIES"),
                            ("data_properties", "DATA PROPERTIES")]:
            c = comparison[key]
            pfx = key.split("_")[0][:1] + key.split("_")[-1][:1]  # not used
            m   = comparison["metrics"]
            prefix = {"classes": "classes", "object_properties": "oprops",
                      "data_properties": "dprops"}[key]
            f.write(f"{label}\n{thin}\n")
            f.write(f"  Gold      : {len(c['gold'])}\n")
            f.write(f"  Extracted : {len(c['extracted'])}\n")
            f.write(f"  Correct   : {len(c['correct'])}\n")
            f.write(f"  Missing   : {len(c['missing'])}\n")
            f.write(f"  Extra     : {len(c['extra'])}\n")
            if c['missing']:
                f.write(f"  Missing items : {', '.join(c['missing'])}\n")
            if c['extra']:
                f.write(f"  Extra items   : {', '.join(c['extra'])}\n")
            f.write(f"  Precision : {m[prefix+'_precision']:.1%}  "
                    f"Recall : {m[prefix+'_recall']:.1%}  "
                    f"F1 : {m[prefix+'_f1']:.1%}\n\n")

        # Restrictions
        r = comparison["restrictions"]
        f.write(f"RESTRICTION AXIOMS\n{thin}\n")
        f.write(f"  Gold      : {r['gold_count']}\n")
        f.write(f"  Extracted : {r['extracted_count']}\n")
        f.write(f"  Correct   : {r['correct_count']}\n")
        f.write(f"  Missing   : {r['missing_count']}\n")
        f.write(f"  Extra     : {r['extra_count']}\n")
        m = comparison["metrics"]
        f.write(f"  Precision : {m['restrictions_precision']:.1%}  "
                f"Recall : {m['restrictions_recall']:.1%}  "
                f"F1 : {m['restrictions_f1']:.1%}\n")
        if r['missing_details']:
            f.write("\n  MISSING (in gold, not extracted):\n")
            for rx in r['missing_details']:
                f.write(f"    - {_restr_human(rx)}\n")
        if r['extra_details']:
            f.write("\n  EXTRA (extracted, not in gold):\n")
            for rx in r['extra_details']:
                f.write(f"    - {_restr_human(rx)}\n")
        f.write("\n")

        # Overall
        f.write(sep + "\nOVERALL METRICS (includes restrictions)\n" + sep + "\n")
        f.write(f"  Precision : {m['overall_precision']:.1%}\n")
        f.write(f"  Recall    : {m['overall_recall']:.1%}\n")
        f.write(f"  F1        : {m['overall_f1']:.1%}\n\n")

        # Mismatch notes
        f.write(sep + "\nMISMATCH NOTES\n" + sep + "\n")
        for note in comparison["mismatch_notes"]:
            f.write(f"  [{note['severity']}] {note['category']} — {note['element']}\n")
            f.write(f"    {note['note']}\n\n")


def _save_csv(comparison, csv_file):
    with open(csv_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["Element Type", "Severity", "Item", "Note"])
        for note in comparison["mismatch_notes"]:
            writer.writerow([note["category"], note["severity"],
                             note["element"], note["note"]])


# ─── Excel report ─────────────────────────────────────────────────────────────

def save_excel_report(comparison, output_file):
    """Save full Excel report with 6 sheets."""
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    HDR_FILL  = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
    HDR_FONT  = Font(bold=True, color="FFFFFF")
    GOOD_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
    BAD_FILL  = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
    WARN_FILL = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
    BOLD      = Font(bold=True)

    def hdr_row(ws, row, cols):
        for col, val in enumerate(cols, 1):
            c = ws.cell(row=row, column=col)
            c.value = val
            c.fill  = HDR_FILL
            c.font  = HDR_FONT
            c.alignment = Alignment(horizontal="center")

    def pct_cell(ws, row, col, val):
        c = ws.cell(row=row, column=col)
        c.value = val
        c.number_format = '0.00%'
        c.alignment = Alignment(horizontal="center")
        if val >= 0.999:
            c.fill = GOOD_FILL
        elif val == 0.0:
            c.fill = BAD_FILL
        elif val < 0.75:
            c.fill = WARN_FILL

    # ── Sheet 1: Summary ────────────────────────────────────────────────────
    ws = wb.create_sheet("Summary", 0)
    for col, w in zip("ABCDEFGHI", [28, 8, 11, 6, 6, 6, 11, 9, 9]):
        ws.column_dimensions[col].width = w

    hdr_row(ws, 1, ["Element Type", "Gold", "Extracted", "TP", "FP", "FN",
                    "Precision", "Recall", "F1"])

    rows = [
        ("Classes",           "classes",           "classes"),
        ("Object Properties", "object_properties", "oprops"),
        ("Data Properties",   "data_properties",   "dprops"),
        ("Restriction Axioms","restrictions",       "restrictions"),
    ]

    for r_idx, (label, ckey, mkey) in enumerate(rows, 2):
        if ckey == "restrictions":
            g = comparison["restrictions"]["gold_count"]
            e = comparison["restrictions"]["extracted_count"]
            tp = comparison["restrictions"]["correct_count"]
            fp = comparison["restrictions"]["extra_count"]
            fn = comparison["restrictions"]["missing_count"]
        else:
            g  = len(comparison[ckey]["gold"])
            e  = len(comparison[ckey]["extracted"])
            tp = len(comparison[ckey]["correct"])
            fp = len(comparison[ckey]["extra"])
            fn = len(comparison[ckey]["missing"])
        m = comparison["metrics"]
        ws.cell(row=r_idx, column=1).value = label
        ws.cell(row=r_idx, column=2).value = g
        ws.cell(row=r_idx, column=3).value = e
        ws.cell(row=r_idx, column=4).value = tp
        ws.cell(row=r_idx, column=5).value = fp
        ws.cell(row=r_idx, column=6).value = fn
        pct_cell(ws, r_idx, 7, m[f"{mkey}_precision"])
        pct_cell(ws, r_idx, 8, m[f"{mkey}_recall"])
        pct_cell(ws, r_idx, 9, m[f"{mkey}_f1"])

    # Overall row
    r_idx += 1
    ws.cell(row=r_idx, column=1).value = "OVERALL (incl. restrictions)"
    ws.cell(row=r_idx, column=1).font  = BOLD
    pct_cell(ws, r_idx, 7, comparison["metrics"]["overall_precision"])
    pct_cell(ws, r_idx, 8, comparison["metrics"]["overall_recall"])
    pct_cell(ws, r_idx, 9, comparison["metrics"]["overall_f1"])

    # ── Sheet 2: Mismatch Notes (NEW) ───────────────────────────────────────
    ws = wb.create_sheet("Mismatch Notes", 1)
    ws.column_dimensions['A'].width = 20
    ws.column_dimensions['B'].width = 18
    ws.column_dimensions['C'].width = 40
    ws.column_dimensions['D'].width = 70

    hdr_row(ws, 1, ["Category", "Severity", "Element", "Explanation"])
    ws.row_dimensions[1].height = 18

    SEV_FILLS = {
        "FALSE NEGATIVE": PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid"),
        "FALSE POSITIVE": PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid"),
        "NONE":           PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid"),
    }

    for row_i, note in enumerate(comparison["mismatch_notes"], 2):
        ws.cell(row=row_i, column=1).value = note["category"]
        ws.cell(row=row_i, column=2).value = note["severity"]
        ws.cell(row=row_i, column=3).value = note["element"]
        ws.cell(row=row_i, column=4).value = note["note"]
        sev_fill = SEV_FILLS.get(note["severity"])
        if sev_fill:
            ws.cell(row=row_i, column=2).fill = sev_fill
        ws.cell(row=row_i, column=4).alignment = Alignment(wrap_text=True)
        ws.row_dimensions[row_i].height = 45

    # ── Sheet 3: Classes ────────────────────────────────────────────────────
    _detail_sheet(wb, "Classes", 2, comparison["classes"],
                  comparison["metrics"], "classes",
                  HDR_FILL, HDR_FONT, GOOD_FILL, BAD_FILL)

    # ── Sheet 4: Object Properties ──────────────────────────────────────────
    _detail_sheet(wb, "Object Properties", 3, comparison["object_properties"],
                  comparison["metrics"], "oprops",
                  HDR_FILL, HDR_FONT, GOOD_FILL, BAD_FILL)

    # ── Sheet 5: Data Properties ────────────────────────────────────────────
    _detail_sheet(wb, "Data Properties", 4, comparison["data_properties"],
                  comparison["metrics"], "dprops",
                  HDR_FILL, HDR_FONT, GOOD_FILL, BAD_FILL)

    # ── Sheet 6: Restrictions ───────────────────────────────────────────────
    ws = wb.create_sheet("Restrictions", 5)
    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 55
    ws.column_dimensions['C'].width = 15

    hdr_row(ws, 1, ["Property", "Restriction Details", "Status"])

    row = 2
    for r in comparison["restrictions"]["matched_details"]:
        ws.cell(row=row, column=1).value = r.get("on_property", "")
        ws.cell(row=row, column=2).value = str(r.get("restriction_details", {}))
        c = ws.cell(row=row, column=3)
        c.value = "CORRECT"
        c.fill  = GOOD_FILL
        c.alignment = Alignment(horizontal="center")
        row += 1

    for r in comparison["restrictions"]["missing_details"]:
        ws.cell(row=row, column=1).value = r.get("on_property", "")
        ws.cell(row=row, column=2).value = str(r.get("restriction_details", {}))
        c = ws.cell(row=row, column=3)
        c.value = "MISSING (FN)"
        c.fill  = BAD_FILL
        c.alignment = Alignment(horizontal="center")
        row += 1

    for r in comparison["restrictions"]["extra_details"]:
        ws.cell(row=row, column=1).value = r.get("on_property", "")
        ws.cell(row=row, column=2).value = str(r.get("restriction_details", {}))
        c = ws.cell(row=row, column=3)
        c.value = "EXTRA (FP)"
        c.fill  = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
        c.alignment = Alignment(horizontal="center")
        row += 1

    if row == 2:
        ws.cell(row=2, column=1).value = "No restrictions in either file"

    # Add P/R/F1 summary at bottom
    row += 1
    ws.cell(row=row, column=1).value = "Precision"
    ws.cell(row=row, column=2).value = f"{comparison['metrics']['restrictions_precision']:.1%}"
    row += 1
    ws.cell(row=row, column=1).value = "Recall"
    ws.cell(row=row, column=2).value = f"{comparison['metrics']['restrictions_recall']:.1%}"
    row += 1
    ws.cell(row=row, column=1).value = "F1"
    ws.cell(row=row, column=2).value = f"{comparison['metrics']['restrictions_f1']:.1%}"

    wb.save(output_file)


def _detail_sheet(wb, sheet_name, sheet_idx, elem_data, metrics, mkey,
                  HDR_FILL, HDR_FONT, GOOD_FILL, BAD_FILL):
    """Build a detail sheet for classes / object props / data props."""
    WARN_FILL = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
    ws = wb.create_sheet(sheet_name, sheet_idx)
    ws.column_dimensions['A'].width = 30
    ws.column_dimensions['B'].width = 15

    # Summary counts
    hdr_row_cells = ["Gold", "Extracted", "TP", "FP", "FN",
                     "Precision", "Recall", "F1"]
    for col, val in enumerate(hdr_row_cells, 1):
        c = ws.cell(row=1, column=col)
        c.value = val
        c.fill  = HDR_FILL
        c.font  = HDR_FONT
        c.alignment = Alignment(horizontal="center")

    g  = len(elem_data["gold"])
    e  = len(elem_data["extracted"])
    tp = len(elem_data["correct"])
    fp = len(elem_data["extra"])
    fn = len(elem_data["missing"])
    for col, val in enumerate([g, e, tp, fp, fn], 1):
        ws.cell(row=2, column=col).value = val
        ws.cell(row=2, column=col).alignment = Alignment(horizontal="center")

    for col, mk in enumerate(["precision", "recall", "f1"], 6):
        c = ws.cell(row=2, column=col)
        v = metrics[f"{mkey}_{mk}"]
        c.value = v
        c.number_format = '0.00%'
        c.alignment = Alignment(horizontal="center")
        if v >= 0.999:  c.fill = GOOD_FILL
        elif v == 0.0:  c.fill = BAD_FILL
        elif v < 0.75:  c.fill = WARN_FILL

    # Item-level listing
    row = 4
    sections = [
        ("Correct (TP)", elem_data["correct"], GOOD_FILL),
        ("Missing in Extraction (FN)", elem_data["missing"], BAD_FILL),
        ("Extra in Extraction (FP)",   elem_data["extra"],   WARN_FILL),
    ]
    for section_label, items, fill in sections:
        ws.cell(row=row, column=1).value = section_label
        ws.cell(row=row, column=1).font  = Font(bold=True)
        ws.cell(row=row, column=1).fill  = fill
        row += 1
        if items:
            for item in items:
                ws.cell(row=row, column=1).value = item
                row += 1
        else:
            ws.cell(row=row, column=1).value = "(none)"
            row += 1
        row += 1


# ─── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python owl_compare.py <extracted.owl> <gold.owl> [output_dir]")
        sys.exit(1)

    extracted_file = sys.argv[1]
    gold_file      = sys.argv[2]
    output_dir     = sys.argv[3] if len(sys.argv) > 3 else "results_owl_comparison"

    for f in [extracted_file, gold_file]:
        if not Path(f).exists():
            print(f"[!] File not found: {f}")
            sys.exit(1)

    print(f"\nComparing OWL files...")
    print(f"  Extracted : {extracted_file}")
    print(f"  Gold      : {gold_file}")
    print(f"  Output    : {output_dir}\n")

    comparison = compare_ontologies(extracted_file, gold_file)
    if not comparison:
        print("[!] Comparison failed")
        sys.exit(1)

    save_results(comparison, output_dir)

    m = comparison["metrics"]
    print(f"\nMetrics Summary:")
    print(f"  {'Element':<25} {'Prec':>7} {'Rec':>7} {'F1':>7}")
    print(f"  {'-'*46}")
    for label, pfx in [("Classes", "classes"), ("Object Properties", "oprops"),
                        ("Data Properties", "dprops"), ("Restrictions", "restrictions"),
                        ("OVERALL", "overall")]:
        print(f"  {label:<25} {m[pfx+'_precision']:>7.1%} "
              f"{m[pfx+'_recall']:>7.1%} {m[pfx+'_f1']:>7.1%}")

    notes = comparison["mismatch_notes"]
    fn_count = sum(1 for n in notes if n["severity"] == "FALSE NEGATIVE")
    fp_count = sum(1 for n in notes if n["severity"] == "FALSE POSITIVE")
    print(f"\nMismatch summary: {fn_count} false negatives, {fp_count} false positives")
    for n in notes:
        if n["severity"] != "NONE":
            print(f"  [{n['severity']}] {n['category']}: {n['element']}")
    print()
